"""Public pipeline for generate-v2 benchmark package assembly."""

from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Any

from .backends.registry import run_simulator_backend
from .catalog import _load_simulator_catalog
from .request import validate_benchmark_request
from .shared import (
    DEFAULT_OUTPUT_DIR,
    PROFILE_SPECS,
    ResolvedBenchmarkRequest,
    _copy_file,
    _copy_tree,
    _load_json_object,
    _relative_posix,
    _validate_json_instance,
    _write_json,
)

INFERENCE_DATASET_MANIFEST_SCHEMA = (
    Path(__file__).resolve().parents[4]
    / "inference_catalog"
    / "schemas"
    / "dataset-manifest.schema.json"
)


def _run_simulator(
    *,
    request: ResolvedBenchmarkRequest,
    seed: int,
    stage_dir: Path,
) -> Path:
    return run_simulator_backend(
        request=request,
        seed=seed,
        stage_dir=stage_dir,
    )


def _dataset_manifest_payload(
    *,
    dataset_id: str,
    request: ResolvedBenchmarkRequest,
    simulator_manifest: dict[str, Any],
) -> dict[str, Any]:
    expression = simulator_manifest["expression"]
    extras = simulator_manifest.get("extras", {})
    spec_profile = PROFILE_SPECS[request.profile]
    dataset_spec = {
        "schema_version": "1.0",
        "id": dataset_id,
        "name": dataset_id,
        "expression": {
            "genes": expression["genes"],
            "columns": expression["columns"],
            "column_kind": spec_profile.column_kind,
            "expression_profile": spec_profile.expression_profile,
        },
        "organism": dict(request.organism),
    }
    payload: dict[str, Any] = {
        "schema_version": "1.0",
        "id": f"{dataset_id}_manifest",
        "dataset": {
            "spec": dataset_spec,
            "expression_matrix": "expression.tsv",
        },
        "extras": {},
    }
    for key in ("groups", "lineage_tree", "tf_list", "prior_grn_by_group"):
        value = extras.get(key)
        if value is not None:
            payload["extras"][key] = value
    if request.notes:
        payload["notes"] = request.notes
    return payload


def _ground_truth_manifest_payload(
    *,
    dataset_id: str,
    request: ResolvedBenchmarkRequest,
    simulator_manifest: dict[str, Any],
) -> dict[str, Any]:
    truth = simulator_manifest["truth"]
    return {
        "schema_version": "1.0",
        "dataset_id": dataset_id,
        "simulator_id": request.simulator_id,
        "profile": request.profile,
        "outputs": {
            "global_network": truth.get("global_network"),
            "legacy_binary_matrix": truth.get("legacy_binary_matrix"),
            "group_networks": [
                {
                    "group": str(item["group"]),
                    "path": str(item["path"]),
                }
                for item in truth.get("group_networks", [])
            ],
        },
        "notes": "Truth package generated by generate-v2.",
    }


def _simulator_run_payload(
    *,
    dataset_id: str,
    seed: int,
    request: ResolvedBenchmarkRequest,
    simulator_manifest: dict[str, Any],
) -> dict[str, Any]:
    return {
        "schema_version": "1.0",
        "dataset_id": dataset_id,
        "benchmark_id": request.request_id,
        "simulator_id": request.simulator_id,
        "profile": request.profile,
        "seed": seed,
        "input_files": request.input_files,
        "simulator_params": request.simulator_params,
        "requested_extras": request.requested_extras,
        "effective_extras": request.effective_extras,
        "docker_image": request.simulator_spec.get("docker_image"),
        "execution_backend": "docker_generate_v2",
        "simulator_output": simulator_manifest,
    }


def _copy_dataset_from_stage(
    *,
    stage_dir: Path,
    dataset_dir: Path,
    dataset_manifest_payload: dict[str, Any],
    ground_truth_manifest_payload: dict[str, Any],
    simulator_run_payload: dict[str, Any],
) -> None:
    dataset_dir.mkdir(parents=True, exist_ok=False)
    _copy_file(stage_dir / "expression.tsv", dataset_dir / "expression.tsv")

    stage_extras = stage_dir / "extras"
    if stage_extras.exists():
        _copy_tree(stage_extras, dataset_dir / "extras")

    stage_truth = stage_dir / "truth"
    if stage_truth.exists():
        _copy_tree(stage_truth, dataset_dir / "truth")

    stage_raw = stage_dir / "provenance" / "raw"
    if stage_raw.exists():
        _copy_tree(stage_raw, dataset_dir / "provenance" / "raw")
    stage_progress = stage_dir / "progress.json"
    if stage_progress.exists():
        _copy_file(stage_progress, dataset_dir / "provenance" / "progress.json")

    _copy_file(
        stage_dir / "simulator-output-manifest.json",
        dataset_dir / "provenance" / "simulator-output-manifest.json",
    )
    _write_json(dataset_dir / "dataset-manifest.json", dataset_manifest_payload)
    _write_json(
        dataset_dir / "ground-truth-manifest.json",
        ground_truth_manifest_payload,
    )
    _write_json(dataset_dir / "provenance" / "simulator-run.json", simulator_run_payload)


def validate_generate_v2_request(request_path: Path) -> dict[str, Any]:
    resolved = validate_benchmark_request(request_path)
    return {
        "request_id": resolved.request_id,
        "profile": resolved.profile,
        "simulator_id": resolved.simulator_id,
        "replicates": resolved.replicates,
        "requested_extras": resolved.requested_extras,
        "effective_extras": resolved.effective_extras,
        "input_files": resolved.input_files,
        "simulator_params": resolved.simulator_params,
        "replicate_seeds": resolved.replicate_seeds,
    }


def run_generate_v2(
    *,
    request_path: Path,
    output_dir: Path = DEFAULT_OUTPUT_DIR,
) -> Path:
    resolved = validate_benchmark_request(request_path)
    schemas, _catalog = _load_simulator_catalog()
    benchmark_root = (output_dir / resolved.request_id).resolve()
    if benchmark_root.exists():
        raise ValueError(f"Benchmark output directory already exists: {benchmark_root}")
    datasets_root = benchmark_root / "datasets"
    datasets_root.mkdir(parents=True, exist_ok=False)

    benchmark_datasets: list[dict[str, Any]] = []
    benchmark_artifacts: list[dict[str, Any]] = []
    with tempfile.TemporaryDirectory(prefix="geneci_generate_v2_") as tmp:
        staging_root = Path(tmp) / "staging"
        staging_root.mkdir(parents=True, exist_ok=True)

        for idx, seed in enumerate(resolved.replicate_seeds, start=1):
            dataset_id = f"{resolved.request_id}__{idx:02d}"
            stage_dir = staging_root / dataset_id
            stage_dir.mkdir(parents=True, exist_ok=True)

            simulator_manifest_path = _run_simulator(
                request=resolved,
                seed=seed,
                stage_dir=stage_dir,
            )
            simulator_manifest = _load_json_object(
                simulator_manifest_path, f"simulator-output-manifest[{dataset_id}]"
            )
            _validate_json_instance(
                instance=simulator_manifest,
                schema=schemas["simulator_output_manifest"],
                label=f"simulator-output-manifest[{dataset_id}]",
            )

            dataset_manifest_payload = _dataset_manifest_payload(
                dataset_id=dataset_id,
                request=resolved,
                simulator_manifest=simulator_manifest,
            )
            ground_truth_manifest_payload = _ground_truth_manifest_payload(
                dataset_id=dataset_id,
                request=resolved,
                simulator_manifest=simulator_manifest,
            )
            simulator_run_payload = _simulator_run_payload(
                dataset_id=dataset_id,
                seed=seed,
                request=resolved,
                simulator_manifest=simulator_manifest,
            )

            inference_dataset_schema = _load_json_object(
                INFERENCE_DATASET_MANIFEST_SCHEMA, "dataset-manifest.schema"
            )
            _validate_json_instance(
                instance=dataset_manifest_payload,
                schema=inference_dataset_schema,
                label=f"dataset-manifest[{dataset_id}]",
            )
            _validate_json_instance(
                instance=ground_truth_manifest_payload,
                schema=schemas["ground_truth_manifest"],
                label=f"ground-truth-manifest[{dataset_id}]",
            )

            dataset_dir = datasets_root / dataset_id
            _copy_dataset_from_stage(
                stage_dir=stage_dir,
                dataset_dir=dataset_dir,
                dataset_manifest_payload=dataset_manifest_payload,
                ground_truth_manifest_payload=ground_truth_manifest_payload,
                simulator_run_payload=simulator_run_payload,
            )

            benchmark_datasets.append(
                {
                    "dataset_id": dataset_id,
                    "seed": seed,
                    "path": _relative_posix(dataset_dir, benchmark_root),
                    "dataset_manifest": _relative_posix(
                        dataset_dir / "dataset-manifest.json", benchmark_root
                    ),
                    "ground_truth_manifest": _relative_posix(
                        dataset_dir / "ground-truth-manifest.json", benchmark_root
                    ),
                }
            )
            benchmark_artifacts.append(
                {
                    "dataset_id": dataset_id,
                    "expression_matrix": _relative_posix(
                        dataset_dir / "expression.tsv", benchmark_root
                    ),
                    "groups": _relative_posix(
                        dataset_dir / "extras" / "groups.tsv", benchmark_root
                    )
                    if (dataset_dir / "extras" / "groups.tsv").exists()
                    else None,
                    "lineage_tree": _relative_posix(
                        dataset_dir / "extras" / "lineage_tree.tsv", benchmark_root
                    )
                    if (dataset_dir / "extras" / "lineage_tree.tsv").exists()
                    else None,
                    "tf_list": _relative_posix(
                        dataset_dir / "extras" / "tf_list.txt", benchmark_root
                    )
                    if (dataset_dir / "extras" / "tf_list.txt").exists()
                    else None,
                    "prior_grn_by_group": _relative_posix(
                        dataset_dir / "extras" / "prior_grn_by_group.tsv",
                        benchmark_root,
                    )
                    if (dataset_dir / "extras" / "prior_grn_by_group.tsv").exists()
                    else None,
                    "global_network": _relative_posix(
                        dataset_dir / "truth" / "global_network.csv", benchmark_root
                    ),
                    "legacy_binary_matrix": _relative_posix(
                        dataset_dir / "truth" / "legacy" / "global_gs.csv",
                        benchmark_root,
                    ),
                    "group_networks_dir": _relative_posix(
                        dataset_dir / "truth" / "group_networks",
                        benchmark_root,
                    )
                    if (dataset_dir / "truth" / "group_networks").exists()
                    else None,
                }
            )

    benchmark_manifest = {
        "schema_version": "1.0",
        "id": resolved.request_id,
        "profile": resolved.profile,
        "simulator_id": resolved.simulator_id,
        "replicates": resolved.replicates,
        "organism": resolved.organism,
        "requested_extras": resolved.requested_extras,
        "effective_extras": resolved.effective_extras,
        "base_seed": resolved.base_seed,
        "input_files": resolved.input_files,
        "resolved_simulator_params": resolved.simulator_params,
        "datasets": benchmark_datasets,
        "artifacts": benchmark_artifacts,
    }
    if resolved.notes:
        benchmark_manifest["notes"] = resolved.notes
    _validate_json_instance(
        instance=benchmark_manifest,
        schema=schemas["benchmark_manifest"],
        label=f"benchmark-manifest[{resolved.request_id}]",
    )
    _write_json(benchmark_root / "benchmark-manifest.json", benchmark_manifest)
    return benchmark_root
