import math
import multiprocessing
import shutil
from pathlib import Path
from typing import List, Optional

import matplotlib as mpl
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from rich import print

from geneci.config import tag, temp_folder_str as default_temp_folder_str
from geneci.core.utils.cpu import get_optimal_cpu_distribution
from geneci.core.utils.docker import (
    available_images,
    client,
    get_volume,
    wait_and_close_container,
)
from geneci.core.utils.io import (
    get_gene_names_from_conf_list,
    get_gene_names_from_expression_file,
)
from geneci.core.utils.plotting import chord_diagram
from geneci.enums import (
    Algorithm,
    CutOffCriteria,
    MemeticDistanceType,
    Technique,
)


def _plot_optimization(
    fun_file: Path,
    fitness_evolution_file: Path,
    plot_fitness_evolution: bool = True,
    plot_pareto_front: bool = True,
    plot_parallel_coordinates: bool = True,
    plot_chord_diagram: bool = True,
    only_files: bool = False,
    output_dir: Path = "<<fun_file>>/..",
):
    """Render optimization artifacts generated by consensus search."""

    mpl.use("WebAgg")

    if str(output_dir) == "<<fun_file>>/..":
        output_dir = Path(fun_file).parent
    Path(output_dir).mkdir(exist_ok=True, parents=True)

    functions = pd.read_csv(fun_file, nrows=0).columns.tolist()

    if plot_fitness_evolution:
        if len(functions) == 1:
            r = 1
            c = 1
        elif len(functions) == 2:
            r = 1
            c = 2
        else:
            r = math.ceil(len(functions) / 2)
            c = 2
        fig = make_subplots(rows=r, cols=c, subplot_titles=functions)

        df = pd.read_csv(fitness_evolution_file, header=None)

        for i, fitness in df.iterrows():
            curr_row = math.ceil((i + 1) / c)
            curr_col = (i + 1) - (c * (curr_row - 1))

            fig.add_trace(
                go.Scatter(x=list(range(len(fitness))), y=fitness),
                row=curr_row,
                col=curr_col,
            )
            fig.update_xaxes(title_text="Generation", row=curr_row, col=curr_col)
            fig.update_yaxes(title_text="Fitness", row=curr_row, col=curr_col)

        fig.update_layout(title_text="Fitness evolution", showlegend=False)
        fig.write_html(f"{output_dir}/fitness_evolution.html")
        if not only_files:
            fig.show()

    if plot_pareto_front:
        if len(functions) != 2 and len(functions) != 3:
            print(
                "[bold yellow]Warning:[/bold yellow] The Pareto front cannot be represented if the number of objectives is other than 2 or 3. Your intention will be ignored."
            )
        else:
            df = pd.read_csv(fun_file)

            if len(functions) == 2:
                fitness_o1 = df[functions[0]].tolist()
                fitness_o2 = df[functions[1]].tolist()

                sorted_idx = np.argsort(fitness_o1)

                fitness_o1 = [fitness_o1[i] for i in sorted_idx]
                fitness_o2 = [fitness_o2[i] for i in sorted_idx]

                fig = px.line(
                    x=fitness_o1, y=fitness_o2, markers=True, title="Pareto front"
                )
                fig.update_xaxes(title_text=functions[0])
                fig.update_yaxes(title_text=functions[1])
                fig.write_html(f"{output_dir}/pareto_front.html")
                if not only_files:
                    fig.show()

            elif len(functions) == 3:
                fig = go.Figure(
                    data=[
                        go.Scatter3d(
                            x=df[functions[0]],
                            y=df[functions[1]],
                            z=df[functions[2]],
                            mode="markers",
                        )
                    ]
                )

                fig.update_layout(
                    scene=dict(
                        xaxis_title=functions[0],
                        yaxis_title=functions[1],
                        zaxis_title=functions[2],
                        xaxis_title_font=dict(size=20),
                        yaxis_title_font=dict(size=20),
                        zaxis_title_font=dict(size=20),
                        xaxis=dict(tickfont=dict(size=14)),
                        yaxis=dict(tickfont=dict(size=14)),
                        zaxis=dict(tickfont=dict(size=14)),
                    ),
                    title="Pareto front",
                )

                fig.write_html(f"{output_dir}/pareto_front.html")
                if not only_files:
                    fig.show()

    if plot_parallel_coordinates:
        if len(functions) == 1:
            print(
                "[bold yellow]Warning:[/bold yellow] Cannot graph parallel coordinates for a single fitness function. Your intention will be ignored."
            )
        else:
            df = pd.read_csv(fun_file)

            fig = px.parallel_coordinates(
                df, dimensions=functions, title="Graph of parallel coordinates"
            )
            fig.write_html(f"{output_dir}/parallel_coordinates.html")
            if not only_files:
                fig.show()

    if plot_chord_diagram and not only_files:
        if len(functions) == 1:
            print(
                "[bold yellow]Warning:[/bold yellow] Cannot graph chord plot for a single fitness function. Your intention will be ignored."
            )
        else:
            df = pd.read_csv(fun_file)

            for feature_name in df.columns:
                max_value = df[feature_name].max()
                min_value = df[feature_name].min()
                df[feature_name] = (df[feature_name] - min_value) / (
                    max_value - min_value
                )

            chord_diagram(df, nbins=24)


def infer_network(
    expression_data: Path,
    technique: Optional[List[Technique]],
    threads: int = multiprocessing.cpu_count(),
    str_threads: str = None,
    temp_folder_str: str = default_temp_folder_str,
    output_dir: Path = Path("./inferred_networks"),
):
    """Infer gene regulatory networks from expression data using selected techniques."""

    if str_threads:
        try:
            cores_ids = [int(i) for i in str_threads.split(",")]
        except Exception as exc:
            raise ValueError(
                "The str_threads variable must be a comma-separated list of integers."
            ) from exc
    else:
        cores_ids = list(range(threads))
    cpus_dict = get_optimal_cpu_distribution(technique, cores_ids)

    print(
        f"\n Infer network from {expression_data.name} with {len(technique)} techniques and saving results in {output_dir}"
    )
    print(f"\n Total cores: {len(cores_ids)}")
    print("Distribution:")
    print(cpus_dict)

    tmp_folder = Path(temp_folder_str)
    tmp_folder.mkdir(exist_ok=True, parents=True)

    tmp_exp_dir = f"./{temp_folder_str}/{Path(expression_data).name}"
    shutil.copyfile(expression_data, tmp_exp_dir)

    containers = []
    for tec in technique:
        print(f"\n Infer network from {expression_data} with {tec.value}")

        if tec == Technique.GENIE3_RF:
            image = f"adriansegura99/geneci_infer-network_genie3:{tag}"
            variant = "RF"
        elif tec == Technique.GRNBOOST2:
            image = f"adriansegura99/geneci_infer-network_genie3:{tag}"
            variant = "GBM"
        elif tec == Technique.GENIE3_ET:
            image = f"adriansegura99/geneci_infer-network_genie3:{tag}"
            variant = "ET"
        else:
            image = f"adriansegura99/geneci_infer-network_{tec.value.lower()}:{tag}"
            variant = None

        if tec in [
            Technique.JUMP3,
            Technique.NARROMI,
            Technique.CMI2NI,
            Technique.RSNET,
            Technique.PCACMI,
            Technique.LOCPCACMI,
            Technique.PLSNET,
            Technique.GRNVBEM,
        ]:
            command = f"/tmp/.X11-unix/{tmp_exp_dir} /tmp/.X11-unix/{temp_folder_str}"
            is_matlab = True
        else:
            command = f"{tmp_exp_dir} {temp_folder_str}"
            if variant:
                command += f" {variant}"
            is_matlab = False

        if image not in available_images:
            print("Downloading docker image ...")
            client.images.pull(repository=image)

        container = client.containers.run(
            image=image,
            volumes=get_volume(temp_folder_str, is_matlab),
            command=command,
            detach=True,
            tty=True,
            cpuset_cpus=",".join([str(i) for i in cpus_dict[tec]]),
        )

        containers.append(container)

    str_times = ""
    for i, container in enumerate(containers):
        logs, execution_time = wait_and_close_container(container)

        str_times += "\t- " + technique[i].value + ":\t" + str(execution_time) + "\n"

        print(logs)

    Path(tmp_exp_dir).unlink()

    measurements_folder = Path(f"./{output_dir}/{expression_data.stem}/measurements/")
    measurements_folder.mkdir(exist_ok=True, parents=True)

    with open(f"./{measurements_folder}/techniques_times.txt", "w") as f:
        f.write("Infer gene regulatory network with available techniques: \n")
        f.write(str_times + "\n")

    output_folder = Path(f"./{output_dir}/{expression_data.stem}/lists/")
    output_folder.mkdir(exist_ok=True, parents=True)

    for f in tmp_folder.glob("*"):
        shutil.move(f, f"{output_folder}/{f.name}")
    tmp_folder.rmdir()

    gene_names = f"./{output_dir}/{expression_data.stem}/gene_names.txt"

    if not Path(gene_names).is_file():
        gene_list = get_gene_names_from_expression_file(expression_data)

        with open(gene_names, "w") as f:
            f.write(",".join(gene_list))


def apply_consensus(
    confidence_list: Optional[List[str]],
    gene_names: Path = None,
    time_series: Path = None,
    known_interactions: Path = None,
    crossover_probability: float = 0.9,
    num_parents: int = 3,
    mutation_probability: float = -1,
    mutation_strength: float = 0.1,
    memetic_distance_type: MemeticDistanceType = MemeticDistanceType.all,
    memetic_probability: float = 0.55,
    population_size: int = 100,
    num_evaluations: int = 25000,
    cut_off_criteria: CutOffCriteria = CutOffCriteria.PercLinksWithBestConf,
    cut_off_value: float = 0.4,
    function: Optional[List[str]] = None,
    reference_point: str = "-",
    algorithm: Algorithm = None,
    threads: int = None,
    plot_results: bool = True,
    compare_performance: Path = None,
    output_dir: Path = "<<conf_list_path>>/../ea_consensus",
):
    """Analyze confidence lists and build a consensus network with evolutionary optimization."""

    print(f"\n Optimize ensemble for {confidence_list}")

    if len(confidence_list) < 2:
        raise ValueError("Insufficient number of confidence lists provided")

    str_functions = ";".join(function)

    if mutation_probability == -1:
        mutation_probability = 1 / len(confidence_list)

    Path(f"{default_temp_folder_str}/lists").mkdir(exist_ok=True, parents=True)

    for file in confidence_list:
        shutil.copyfile(file, f"{default_temp_folder_str}/lists/{Path(file).name}")

    tmp_gene_names_dir = f"{default_temp_folder_str}/gene_names.txt"

    if gene_names:
        shutil.copyfile(gene_names, tmp_gene_names_dir)
    else:
        gene_list = set()

        for file in confidence_list:
            gene_list.update(get_gene_names_from_conf_list(file))

        with open(tmp_gene_names_dir, "w") as f:
            f.write(",".join(sorted(gene_list)))

    tmp_time_series_dir = f"{default_temp_folder_str}/time_series.csv"
    if time_series:
        shutil.copyfile(time_series, tmp_time_series_dir)

    tmp_known_interactions_dir = f"{default_temp_folder_str}/known_interactions.csv"
    if known_interactions:
        shutil.copyfile(known_interactions, tmp_known_interactions_dir)

    tmp_reference_front_dir = f"{default_temp_folder_str}/reference_front.csv"
    if compare_performance:
        shutil.copyfile(compare_performance, tmp_reference_front_dir)

    image = f"adriansegura99/geneci_optimize-ensemble:{tag}"

    if image not in available_images:
        print("Downloading docker image ...")
        client.images.pull(repository=image)

    container = client.containers.run(
        image=image,
        volumes=get_volume(default_temp_folder_str),
        command=f"{default_temp_folder_str} {crossover_probability} {num_parents} {mutation_probability} {mutation_strength} {population_size} {num_evaluations} {cut_off_criteria.value} {cut_off_value} {str_functions} {algorithm.value} {threads} {plot_results} {memetic_distance_type.value} {memetic_probability} {reference_point}",
        detach=True,
        tty=True,
    )

    logs, _ = wait_and_close_container(container)
    print(logs)

    if plot_results:
        _plot_optimization(
            fun_file=f"{default_temp_folder_str}/ea_consensus/FUN.csv",
            fitness_evolution_file=f"{default_temp_folder_str}/ea_consensus/fitness_evolution.txt",
            plot_fitness_evolution=True,
            plot_pareto_front=True,
            plot_parallel_coordinates=True,
            plot_chord_diagram=True,
            output_dir="<<fun_file>>/..",
        )

    if compare_performance:
        with open(f"{default_temp_folder_str}/ea_consensus/compare_performance.txt", "r") as file:
            line = file.readline().strip()

        data = list(map(float, line.split(",")))

        fig = go.Figure()
        fig.add_trace(go.Scatter(x=list(range(len(data))), y=data, mode="lines+markers"))

        fig.update_layout(
            title="Data chart",
            xaxis_title="Generation",
            yaxis_title="Percentage of reference front solutions dominated",
        )
        fig.write_html(f"{default_temp_folder_str}/ea_consensus/compare_performance.html")

    if str(output_dir) == "<<conf_list_path>>/../ea_consensus":
        output_dir = f"{Path(confidence_list[0]).parent.parent}/ea_consensus"
    Path(output_dir).mkdir(exist_ok=True, parents=True)

    for f in Path(f"{default_temp_folder_str}/ea_consensus").glob("*"):
        shutil.move(f, f"{output_dir}/{f.name}")
    shutil.rmtree(default_temp_folder_str)


__all__ = ["infer_network", "apply_consensus"]
