name: release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Python 3.13.5
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.5
    - name: Get full Python version
      shell: bash
      run: python -c "import sys; print('.'.join(str(v) for v in sys.version_info[:3]))"
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.1.3
    - name: Build project for distribution
      shell: bash
      run: poetry build
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: steps.check-version.outputs.prerelease == 'true'
