name: Sincronizar a repositorio MO-GENECI

on:
  push:
    branches:
      - v-2.0.1 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
      
      - name: Configurar Git
        run: |
          git config --global user.email "adrianseor.99@uma.es"
          git config --global user.name "AdrianSeguraOrtiz"

      - name: Empujar cambios al repositorio MO-GENECI
        run: |
          git remote add MO-GENECI https://github.com/AdrianSeguraOrtiz/MO-GENECI.git
          git push -u MO-GENECI v-2.0.1:main --force