name: Sincronizar a repositorio BIO-INSIGHT

on:
  push:
    branches:
      - v-3.0.1 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
      
      - name: Configurar Git
        run: |
          git config --global user.email "adrianseor.99@uma.es"
          git config --global user.name "AdrianSeguraOrtiz"

      - name: Empujar cambios al repositorio BIO-INSIGHT
        run: |
          git remote add BIO-INSIGHT https://github.com/AdrianSeguraOrtiz/BIO-INSIGHT.git
          git push -u BIO-INSIGHT v-3.0.1:main --force