name: Sincronizar a repositorio PBEvoGen

on:
  push:
    branches:
      - v-2.5.1 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
      
      - name: Configurar Git
        run: |
          git config --global user.email "adrianseor.99@uma.es"
          git config --global user.name "AdrianSeguraOrtiz"

      - name: Empujar cambios al repositorio PBEvoGen
        run: |
          git remote add PBEvoGen https://github.com/AdrianSeguraOrtiz/PBEvoGen.git
          git push -u PBEvoGen v-2.5.1:main --force